version: "3"

services:
    redis:
        image: redis
        restart: always
        volumes:
        - ./:/usr/src/app/
        ports:
        - 6379:6379
    web:
        build:
            context: ./
            dockerfile: Dockerfile
        volumes:
            - ./:/usr/src/app/
        ports: 
            - '8000:8000'
        env_file:
            - ../VARENV.env