version: "3"

services:
    web:
        build:
            context: ./
            dockerfile: Dockerfile
        volumes:
            - ./:/usr/src/app/
        ports: 
            - '8000:8000'
        env_file:
            - ../VARENV.env