# Generated by Django 3.0.8 on 2021-04-01 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpatient',
            name='movement_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата перемещения'),
        ),
        migrations.AddField(
            model_name='patient',
            name='movement_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата перемещения'),
        ),
    ]
