# Generated by Django 3.0.8 on 2021-04-01 20:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_auto_20210401_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movementhistory',
            name='next_ward_number',
        ),
        migrations.AddField(
            model_name='movementhistory',
            name='prev_ward_number',
            field=models.CharField(help_text='В формате - 010', max_length=4, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Упс... Попробуйте снова', regex='^[0-9]{3}$')], verbose_name='Предыдущая палата'),
        ),
        migrations.AlterField(
            model_name='movementhistory',
            name='current_ward_number',
            field=models.CharField(help_text='В формате - 010', max_length=3, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Упс... Попробуйте снова', regex='^[0-9]{3}$')], verbose_name='Текущая палата'),
        ),
        migrations.AlterField(
            model_name='movementhistory',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='patient.Patient', verbose_name='Пациент'),
        ),
        migrations.AlterField(
            model_name='movementhistory',
            name='ward_movement_date',
            field=models.DateTimeField(null=True, verbose_name='Дата перемещения'),
        ),
    ]
