# Generated by Django 3.0.8 on 2021-04-01 21:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_auto_20210401_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movementhistory',
            name='prev_ward_number',
            field=models.CharField(help_text='В формате - 010', max_length=4, null=True, validators=[django.core.validators.RegexValidator(message='Упс... Попробуйте снова', regex='^[0-9]{3}$')], verbose_name='Предыдущая палата'),
        ),
    ]
