# Generated by Django 3.0.8 on 2021-04-06 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_auto_20210402_0011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalpatient',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Карточка пациента'},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['-created_at'], 'verbose_name': 'Карточка пациента', 'verbose_name_plural': 'Карточки пациентов'},
        ),
        migrations.AlterField(
            model_name='movementhistory',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.Patient', verbose_name='Пациент'),
        ),
    ]
